"""Regenerates static/fonts/ (self-hosted @font-face CSS + woff2 files) from
the upstream @fontsource npm packages.

MyBacklog used to load Space Grotesk / Inter / JetBrains Mono / Atkinson
Hyperlegible from fonts.googleapis.com at runtime. That's a network call on
every launch and a poor fit for a "your data stays local" app, and it fails
closed (ugly fallback fonts, extra latency) on an offline/restricted
network. This script vendors the exact same font files locally instead, so
static/fonts/fonts.css + static/fonts/<family>/files/*.woff2 can just be
committed and served from /static like everything else.

Only needs to be re-run if the font families/weights used by style.css /
index.html ever change (see FONTS below to match). Requires `npm` on PATH;
not part of the app's runtime dependencies.

Usage:
    python3 scripts/build_fonts.py
"""
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "static" / "fonts"

# (npm package, output folder name under static/fonts/, weights actually
# used in static/css/style.css / index.html's font stack)
FONTS = [
    ("@fontsource/space-grotesk", "space-grotesk", [500, 600, 700]),
    ("@fontsource/inter", "inter", [400, 500, 600]),
    ("@fontsource/jetbrains-mono", "jetbrains-mono", [500, 600]),
    ("@fontsource/atkinson-hyperlegible", "atkinson-hyperlegible", [400, 700]),
]

HEADER = (
    "/* Self-hosted fonts (Space Grotesk, Inter, JetBrains Mono, Atkinson\n"
    " * Hyperlegible), generated by scripts/build_fonts.py from the\n"
    " * @fontsource npm packages instead of loading fonts.googleapis.com at\n"
    " * runtime -- MyBacklog runs fully offline/locally, so its fonts\n"
    " * shouldn't depend on a network call to Google on every launch.\n"
    " * latin + latin-ext subsets only (covers English/French accented\n"
    " * characters); other subsets (cyrillic, greek, vietnamese...) are\n"
    " * dropped as unused. woff2 only (all currently-supported browsers).\n"
    " * DO NOT EDIT BY HAND -- rerun this script instead. */\n"
)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        if OUT_DIR.exists():
            shutil.rmtree(OUT_DIR)
        OUT_DIR.mkdir(parents=True)

        all_blocks = []
        for npm_name, slug, weights in FONTS:
            print(f"Fetching {npm_name}...")
            subprocess.run(
                ["npm", "pack", npm_name, "--silent"], cwd=tmp, check=True,
                stdout=subprocess.DEVNULL,
            )
            tgz = next(tmp.glob(f"*{slug}*.tgz"))
            subprocess.run(["tar", "xzf", tgz.name], cwd=tmp, check=True)
            pkg_dir = tmp / "package"

            dest_files_dir = OUT_DIR / slug / "files"
            dest_files_dir.mkdir(parents=True, exist_ok=True)
            shutil.copy(pkg_dir / "LICENSE", OUT_DIR / slug / "OFL-LICENSE.txt")

            for w in weights:
                css_text = (pkg_dir / f"{w}.css").read_text()
                for block in re.findall(r"/\*.*?\*/\s*@font-face\s*\{[^}]*\}", css_text, re.S):
                    comment = re.match(r"/\*\s*(\S+)", block)
                    subset_tag = comment.group(1) if comment else ""
                    if not re.search(r"-(latin|latin-ext)-\d", subset_tag):
                        continue  # drop cyrillic/greek/vietnamese/etc.
                    m = re.search(r"url\(\./files/([^)]+\.woff2)\)", block)
                    if not m:
                        continue
                    fname = m.group(1)
                    block = re.sub(
                        r"src: url\(\./files/[^)]+\.woff2\)[^;]*;",
                        f"src: url(./{slug}/files/{fname}) format('woff2');",
                        block,
                    )
                    all_blocks.append(block.strip())
                    shutil.copy(pkg_dir / "files" / fname, dest_files_dir / fname)

            shutil.rmtree(pkg_dir)
            tgz.unlink()

        (OUT_DIR / "fonts.css").write_text(HEADER + "\n" + "\n\n".join(all_blocks) + "\n")
        print(f"Wrote {OUT_DIR / 'fonts.css'} ({len(all_blocks)} @font-face rules).")


if __name__ == "__main__":
    main()
